# Configuration file for the Bitcoin Passphrase Brute-Force Tool

# Seed phrase used for generating the passphrase
seed_phrase = "anger science wool gown ocean eagle sadness action smooth series goose elder"

# Expected Bitcoin address that should match the generated passphrase
expected_address = "bc1qckqpdax6ys5lf9r84rhkl283xjjemgwl94r7aq" # for no passhphrase: "bc1qy75w3zm24vjmrdue78jf5t9t3r0p52nu049vm9"
expected_masterfingerprint = "60008b2f" #passphrase:9999  # for no passphrase: "88ff8206"

# Path to the directory where the generated wordlist files will be saved
wordlist_path = "wordlists"

# Number of threads to be used for generation
num_threads = 7

# Regex pattern for passphrase generation
# Examples:
# - [A-Z][0-9]{2} - Uppercase letter followed by two digits
# - Q[a-z]{3}[0-9] - Letter Q followed by three lowercase letters and one digit
# - [A-Z]us[A-Z]t[0-9]mz[A-Z]{2}[0-9]{2}QQ - Complex pattern
passphrase = "[0-9]{4,6}"


# Number of address paths to search (1, 2, or 3)
address_paths_to_search = 1